Основы Vue
js-tasks-ru/vue-20230120_elena22 pull request #2
Opened 2023-01-29 18:04 UTC by elmesheryakova

выполнены задачи 1-4

2023-01-29 18:05 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-01-31 20:08 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 20:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 20:28 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 21:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 21:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 22:09 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 22:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-01-31 23:40 UTC, ShGKme requested changes
В `01-basics/02-VueCalculator` требуется привязывать состояние компонента к радиокнопкам и вычислять не 4 результата вычисляемыми свойствами, а результат текущего выражения.

В `01-basics/03-MarkedList` вычисляемые свойства используется некорректно. 

Обе задачи требуется доработать, чтобы разобраться с использованием вычисляемых свойств. `computed` - важный инструмент в разработке Vue компонентов.

В `01-basics/04-MeetupTitle` требуется использовать готовую функцию без её редактирования и переноса в свойства компонента.

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/01-CounterButtonApp/index.html
> +      <button @click="count" type="button">{{counter}}</button>
У текстовой интерполяции обычно принято добавлять пробелы в скобках: `{{ counter }}`

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/02-VueCalculator/index.html
> +          <label><input @click="calc('divide')" type="radio" name="operator" value="divide" /> ➗</label>
Состояние элементов в компоненте должно полностью определяться компонентом. Сейчас выбрана ли радиокнопка не зависит от состояния компонента. Требуется привязывать `checked`. Иначе при ререндеринге может возникнуть ситуация, когда на странице выбрана не так радиокнопка, которая выбрана в состоянии приложения.

Для этого также требуется явно хранить выбранную операцию в состоянии компонента. То, выбран ли сейчас "+" или "-" - тоже часть состояние приложения, это определяет его состояние, работу и то, что пользователь видит на экране.

Вместо привязки `checked` и обработки события изменения можно использовать короткий вариант - директиву `v-model` двусторонней привязки, которая как раз будет привязывать `checked` к свойству и обрабатывать событие изменения `change` (по историческим причинам событие `click` тут тоже работает, но change корректнее)

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Сейчас компонент имеет в своём состоянии сразу все 4 варианта вычисления, хотя нужен один. Но вычисляет без клика пользователя результат непосредственно нужного вычисления.

В вычисляемом свойстве нужно сразу вычислять `output`. Так результат вычисления всегда будет в состоянии компонента, без привязки к конкретному действию пользователя на интерфейсе.

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Это вычисляемое свойство ни разу не вычисляется, так как компонент никогда не обращается к свойству `fullArr`. Но даже при его использовании результат вычисления был бы `undefined`, так как `forEach` ничего не возвращает. А иметь побочные эффекты во время вычисления (изменять другие свойства) вычисляемое свойства нельзя.

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +        }
Метод фильтрации в JS здесь используется некорректно. `filter` должен только проверять, подходит ли элемент под условия фильтрации, возвращая `true` или `false`. Здесь фильтр всегда возвращает пустой массив, но в процессе получения пустого массива изменяет свойства объектов в исходном массиве. В результате метод `filter` используется не как фильтр, а как цикл.

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> -  });
Для использования функции в компоненте её не требуется переносить в методы. В методах компонента должны быть те функции, которые являются частью компонента. Изменяют или используют его свойства, обрабатывают события внутри компонента. Могут в методах также быть и простые функции, если они используются только в других методах этого же компонента и не нужны вне компонента.

Здесь же `fetchMeetupById` - самостоятельная функция.

Самостоятельную функцию могут использовать другие компоненты, функции и прочие модули приложения вне разрабатываемого компонента.

2023-01-31 23:40 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Этот метод всегда при изменении поля поиска обновляет свойства `marked` в массиве `filteredEmails`. Лучше явно описать `filteredEmails`, как вычисляемое свойство, и вычислять в нём массив объектов с актуальным значением `marked`.

2023-01-31 23:40 UTC, ShGKme commented on 02-components/05-MeetupAgenda/components/MeetupAgendaItem.js
> +  },
Эти методы принимают параметр `type`, но в них никогда не передаётся и не может передаваться никакого иного значения, кроме `agendaItem.type`. Лучше заменить эти метод на вычисляемые свойства, которые будут вычислять значения на основе данных компонента.

2023-02-01 21:56 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-02 13:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-02 19:05 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-02 19:08 UTC, merged