решены задачи 1-3 из модуля 04
js-tasks-ru/vue-20230120_elena22 pull request #3
Opened 2023-02-08 09:27 UTC by elmesheryakova

2023-02-08 09:28 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-08 10:35 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-08 22:53 UTC, ShGKme requested changes
В `04-vue-cli/03-UiDropdown1` требуется явно описывать свойства, вычисляемые на основе других свойств, как вычисляемые свойства.

В `04-vue-cli/02-TheToaster` - требуется придумать альтернативу текста сообщения для идентификатора.

Удаление задачи не могу засчитать за решённую задачу...

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</script>
Этот компонент сам отвечает за вывод одного тоста и знает о тостах разных типов. Именно в нём описаны классы   `toast_success` и `toast_error`. В этом случае лучше ему же определять, какие классы и иконки должны быть у разных типов тостов.

Сейчас об этом должен знать пользователь компонента, который должен передать правильное имя класса из исходников компонента и иконку.

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +</script>
Обычно параметры лучше передавать отдельно, не оборачивая их в ещё один объект. Параметры (пропсы) фактически уже объект пар ключ (имя пропса) - значение.

Передача отдельных параметров удобнее пользователю компонента: видны отдельные параметры и их типы без дополнительной документации и TypeScript, не нужно обязательно оборачивать в объект.

```html
<ui-toast :toast="{ icon: 'error', message: 'error' }" />
<ui-toast icon="error" message="error" />
```

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/UiToast.vue
> +  </div>
С событием незачем отдавать `id`, который этому компоненту в целом не нужен. Его родитель итак знает, у какого тоста порождается событие `close`. Он знает этот `id`, который сейчас получается вместе с событием, потому что он сам же ему его отдаёт. Сейчас `id` просто получается от родителя и отправляется ему же обратно.

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
>    </div>
Здесь `TheToaster` передаёт в `UiToast` тост, а потом его же ловит и использует в `@close="closeToats"`. Вместо отправки ID по кругу можно явно передать его сразу: `@close="closeToats(toast.id)"`.

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/02-TheToaster/components/TheToaster.vue
> +    },
Некорректно использовать текст сообщения в качестве идентификатора. В этом случае будут удалены сразу все сообщения с одинаковым текстом. А тексты тостов часто одинаковые, часто это просто "Успешно" или "Сохранено".

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  </select>
Почему `name="city"`?

2023-02-08 22:53 UTC, ShGKme commented on 04-vue-cli/03-UiDropdown1/components/UiDropdown.vue
> +  },
`selectedIcon` - это не совсем самостоятельные, собственные данные компонента.  Значение `selectedIcon` всегда является результатом вычисления от `options` и `modelValue`, то есть это вычисляемое свойство. За этим приходится следить везде, где меняется значение. Например, если поменяется `modelValue` или `options`, `selectedIcon` в вашем решении останется старым.

Реализация `selectedIcon` как вычисляемого свойства получится проще, будет явно описывать, что оно вычисляется, при этом не потребуется самостоятельно думать о том, что отслеживать, чтобы ничего не забыть.

С `value` почти аналогично. Оно используется в `v-model`, но и там не нужна двусторонняя привязка. Достаточно привязать значение `:value="modelValue"`.

2023-02-10 07:11 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2023-02-10 10:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2023-02-10 18:52 UTC, ShGKme approved these changes
Все задачи приняты 👍

2023-02-10 18:54 UTC, merged